import type { FRAClaim, Village, AssetData, PolicyRecommendation } from "./types"

// Mock FRA Claims Data
export const mockFRAClaims: FRAClaim[] = [
  {
    id: "fra-001",
    villageId: "vil-001",
    villageName: "Kanha Village",
    district: "Mandla",
    state: "Madhya Pradesh",
    pattalHolderName: "Ramesh Kumar",
    coordinates: { latitude: 22.3344, longitude: 80.6093 },
    claimType: "IFR",
    status: "granted",
    areaHectares: 2.5,
    submissionDate: "2023-03-15",
    verificationDate: "2023-06-20",
    grantDate: "2023-08-10",
    documents: ["claim_form.pdf", "survey_map.jpg", "identity_proof.pdf", "residence_proof.pdf"],
    ownerDetails: {
      fatherName: "Shyam Kumar",
      age: 45,
      occupation: "Farmer",
      familyMembers: 6,
      contactNumber: "+91-9876543210",
      bankAccount: "SBI-1234567890",
      adharNumber: "XXXX-XXXX-1234",
    },
    landDetails: {
      surveyNumber: "123/4A",
      landType: "Agricultural",
      soilType: "Red Soil",
      irrigation: "Rain-fed",
      crops: ["Rice", "Wheat", "Pulses"],
      nearestRoad: "Village Road - 0.5km",
      nearestWaterSource: "Village Well - 200m",
    },
  },
  {
    id: "fra-002",
    villageId: "vil-002",
    villageName: "Agartala Rural",
    district: "West Tripura",
    state: "Tripura",
    pattalHolderName: "Biplab Debbarma",
    coordinates: { latitude: 23.8315, longitude: 91.2868 },
    claimType: "CFR",
    status: "pending",
    areaHectares: 15.0,
    submissionDate: "2024-01-20",
    documents: ["community_claim.pdf", "village_resolution.pdf", "forest_map.jpg"],
    ownerDetails: {
      fatherName: "Ratna Debbarma",
      age: 52,
      occupation: "Community Leader",
      familyMembers: 8,
      contactNumber: "+91-9876543211",
      bankAccount: "AGVB-2345678901",
      adharNumber: "XXXX-XXXX-2345",
    },
    landDetails: {
      surveyNumber: "456/7B",
      landType: "Forest Land",
      soilType: "Laterite Soil",
      irrigation: "Natural Springs",
      crops: ["Jhum Cultivation", "Bamboo", "Medicinal Plants"],
      nearestRoad: "State Highway - 2km",
      nearestWaterSource: "Natural Spring - 100m",
    },
  },
  {
    id: "fra-003",
    villageId: "vil-003",
    villageName: "Simlipal Buffer",
    district: "Mayurbhanj",
    state: "Odisha",
    pattalHolderName: "Santosh Soren",
    coordinates: { latitude: 21.6637, longitude: 86.229 },
    claimType: "IFR",
    status: "verified",
    areaHectares: 1.8,
    submissionDate: "2023-11-05",
    verificationDate: "2024-02-15",
    documents: ["individual_claim.pdf", "gps_coordinates.txt", "identity_proof.pdf", "residence_proof.pdf"],
    ownerDetails: {
      fatherName: "Krishna Soren",
      age: 50,
      occupation: "Farmer",
      familyMembers: 5,
      contactNumber: "+91-9876543212",
      bankAccount: "BOI-3456789012",
      adharNumber: "XXXX-XXXX-3456",
    },
    landDetails: {
      surveyNumber: "789/0C",
      landType: "Agricultural",
      soilType: "Laterite Soil",
      irrigation: "Rain-fed",
      crops: ["Rice", "Pulses"],
      nearestRoad: "Village Road - 1km",
      nearestWaterSource: "Village Well - 300m",
    },
  },
  {
    id: "fra-004",
    villageId: "vil-004",
    villageName: "Warangal Forest",
    district: "Warangal",
    state: "Telangana",
    pattalHolderName: "Lakshmi Reddy",
    coordinates: { latitude: 17.9689, longitude: 79.5941 },
    claimType: "CR",
    status: "rejected",
    areaHectares: 3.2,
    submissionDate: "2023-07-12",
    verificationDate: "2023-10-30",
    documents: ["claim_rejected.pdf", "identity_proof.pdf", "residence_proof.pdf"],
    ownerDetails: {
      fatherName: "Venkat Reddy",
      age: 48,
      occupation: "Farmer",
      familyMembers: 7,
      contactNumber: "+91-9876543213",
      bankAccount: "ICICI-4567890123",
      adharNumber: "XXXX-XXXX-4567",
    },
    landDetails: {
      surveyNumber: "321/9D",
      landType: "Forest Land",
      soilType: "Black Soil",
      irrigation: "Natural Springs",
      crops: ["Bamboo", "Medicinal Plants"],
      nearestRoad: "State Highway - 3km",
      nearestWaterSource: "Natural Spring - 150m",
    },
  },
]

// Mock Villages Data
export const mockVillages: Village[] = [
  {
    id: "vil-001",
    name: "Kanha Village",
    district: "Mandla",
    state: "Madhya Pradesh",
    coordinates: { latitude: 22.3344, longitude: 80.6093 },
    population: 1250,
    forestCover: 75,
    waterIndex: 0.6,
    claims: [mockFRAClaims[0]],
    assets: [],
  },
  {
    id: "vil-002",
    name: "Agartala Rural",
    district: "West Tripura",
    state: "Tripura",
    coordinates: { latitude: 23.8315, longitude: 91.2868 },
    population: 890,
    forestCover: 45,
    waterIndex: 0.3,
    claims: [mockFRAClaims[1]],
    assets: [],
  },
  {
    id: "vil-003",
    name: "Simlipal Buffer",
    district: "Mayurbhanj",
    state: "Odisha",
    coordinates: { latitude: 21.6637, longitude: 86.229 },
    population: 2100,
    forestCover: 85,
    waterIndex: 0.7,
    claims: [mockFRAClaims[2]],
    assets: [],
  },
  {
    id: "vil-004",
    name: "Warangal Forest",
    district: "Warangal",
    state: "Telangana",
    coordinates: { latitude: 17.9689, longitude: 79.5941 },
    population: 1680,
    forestCover: 35,
    waterIndex: 0.4,
    claims: [mockFRAClaims[3]],
    assets: [],
  },
]

// Mock Asset Data
export const mockAssets: AssetData[] = [
  {
    id: "asset-001",
    coordinates: { latitude: 22.3344, longitude: 80.6093 },
    landUseType: "Forest",
    areaHectares: 150.5,
    confidence: 0.92,
    lastUpdated: "2024-01-15",
    satelliteSource: "Sentinel-2",
  },
  {
    id: "asset-002",
    coordinates: { latitude: 23.8315, longitude: 91.2868 },
    landUseType: "Agriculture",
    areaHectares: 45.2,
    confidence: 0.87,
    lastUpdated: "2024-01-15",
    satelliteSource: "Sentinel-2",
  },
  {
    id: "asset-003",
    coordinates: { latitude: 21.6637, longitude: 86.229 },
    landUseType: "Water",
    areaHectares: 12.8,
    confidence: 0.95,
    lastUpdated: "2024-01-15",
    satelliteSource: "Sentinel-2",
  },
  {
    id: "asset-004",
    coordinates: { latitude: 17.9689, longitude: 79.5941 },
    landUseType: "Degraded",
    areaHectares: 28.3,
    confidence: 0.78,
    lastUpdated: "2024-01-15",
    satelliteSource: "Sentinel-2",
  },
]

// Mock Policy Recommendations
export const mockRecommendations: PolicyRecommendation[] = [
  {
    id: "rec-001",
    villageId: "vil-002",
    villageName: "Agartala Rural",
    recommendationType: "PM-KISAN",
    priority: "High",
    reasoning: "Village has significant agricultural FRA claims with granted patta holders",
    estimatedBenefit: "₹6,000 per year per farmer",
    implementationSteps: [
      "Verify FRA patta holder eligibility",
      "Register farmers in PM-KISAN portal",
      "Link bank accounts for direct benefit transfer",
    ],
    generatedDate: "2024-01-20",
  },
  {
    id: "rec-002",
    villageId: "vil-002",
    villageName: "Agartala Rural",
    recommendationType: "Jal Jeevan Mission",
    priority: "High",
    reasoning: "Low water index (0.3) indicates water scarcity issues",
    estimatedBenefit: "Improved water access for 890 residents",
    implementationSteps: [
      "Conduct water source survey",
      "Install bore wells and water treatment systems",
      "Establish village water committee",
    ],
    generatedDate: "2024-01-20",
  },
  {
    id: "rec-003",
    villageId: "vil-004",
    villageName: "Warangal Forest",
    recommendationType: "MGNREGA",
    priority: "Medium",
    reasoning: "Degraded forest areas identified through satellite imagery analysis",
    estimatedBenefit: "Employment for 200+ households, 28 hectares restored",
    implementationSteps: [
      "Plan afforestation activities",
      "Register households for MGNREGA work",
      "Procure native tree saplings",
      "Implement plantation and maintenance work",
    ],
    generatedDate: "2024-01-20",
  },
]
